server:
  port: 8080

dollar:
  brlValue: ${DOLLAR_BRL-VALUE:5.00}

contaBanco:
  numeroConta: "1"

# Configuracoes do banco de dados H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    sql:
      init:
        mode: always




